### PR TITLE
Add modules from bootcamp23

### PR DESCRIPTION
**Pull request by cosden**
This adds the new repos/pages from the bootcamp to the (currently hidden) curriculum page.

### CODE REVIEW

**Comment by cosden** [comment]
Preview: https://output.circle-artifacts.com/output/job/6dac14e8-24b3-404c-a4d0-ff27bcfefb48/artifacts/0/intersect-training.github.io/curriculum/index.html

I thought this would be easier to have everything in a single place that to go hunting for them. We might want to share it later too.

**Review by JeffCarver — COMMENTED** [review]
Looks good except Testing is in there two times.

**Comment by cosden** [comment]
https://output.circle-artifacts.com/output/job/7f57bd31-e1da-4a02-8e7d-0ee013aacc6b/artifacts/0/intersect-training.github.io/curriculum/index.html

**Review by JeffCarver — COMMENTED** [review]
Looks good.

**Pull request merged**
