### PR TITLE
Add blog post about INTERSECT video

### PR DESCRIPTION
**Pull request by JeffCarver**
I drafted the blog post to focus more on the video than on when the presentation will occur. @cosden if you think we should revise the blog post to be more like the others (or if you have other wording), please edits.

### CODE REVIEW

**Comment by JeffCarver** [comment]
I cannot find the link to the file in the CircleCI build or I would post it here.

**Comment by cosden** [comment]
It's not building a preview because the date (in filename) is in the future. If you make it today's date it should build. It wouldn't display on the website either, until Monday.

**Comment by JeffCarver** [comment]
I changed the filename, but I still don't see it in the preview

**Comment by cosden** [comment]
The preview drops the date. The page is here: https://41-293151248-gh.circle-artifacts.com/0/intersect-training.github.io/announcement/intersect-overview-video/index.html
And it appears on the main page: https://41-293151248-gh.circle-artifacts.com/0/intersect-training.github.io/index.html

**Comment by cosden** [comment]
Post preview: https://42-293151248-gh.circle-artifacts.com/0/intersect-training.github.io/announcement/intersect-overview-video/index.html
Front page: https://42-293151248-gh.circle-artifacts.com/0/intersect-training.github.io/index.html

@JeffCarver - over to you. If you're good with this, I am too.

**Review by cosden — APPROVED** [review]

**Pull request merged**
