### PR TITLE
add public open source tutorials from ENCCS and CodeRefinery

### PR DESCRIPTION
**Pull request by wikfeldt**
Hope these resources fit the scope and will be useful for the community. Happy to revise the PR if anything is missing

### CODE REVIEW

**Comment by cosden** [comment]
@wikfeldt - Wow! Thank you. This looks fantastic! There's so much here, give us a bit to review more closely, but after a quick skim it looks great.

**Comment by cosden** [comment]
CI Preview: https://output.circle-artifacts.com/output/job/b246a435-c9aa-4299-943a-c6b82e881567/artifacts/0/intersect-training.github.io/training-links/index.html

**Comment by wikfeldt** [comment]
Cheers! There are many more [CodeRefinery](https://coderefinery.org/lessons/) and [ENCCS](https://enccs.se/lessons/) lessons but the others not added here probably don't quite fit the scope

**Review by cosden — APPROVED** [review]

**Comment by cosden** [comment]
Thanks again, @wikfeldt. These are excellent resources perfectly in line with what we are trying to accomplish here.

**Pull request merged**
