### PR TITLE
Add Schreiner PyHEP training material

### PR DESCRIPTION
**Pull request by cosden**
Adds two new Python-based training courses from Henry at PyHEP 2021

### CODE REVIEW

**Comment by cosden** [comment]
Preview: https://38-293151248-gh.circle-artifacts.com/0/intersect-training.github.io/training-links/index.html

**Comment by cosden** [comment]
Hey @henryiii, I added your two PyHEP talks to INTERSECT's links page here. Are you good with the change I made on the python packaging one? To be more consistent with the others already there I linked to your notebook that you used in the lecture, and PyHEP description but included the link to the scikit-hep developer notes page in the description. I couldn't figure out how to hyperlink from the .yml file description so it's got the URL. And this is just to capture things for now, it's not permanent (so classification/tags will be edited).

**Comment by henryiii** [comment]
That is fine. :+1: I've opened a PR that shows how to support markdown in the YAML files.

**Comment by cosden** [comment]
New preview looks perfect: https://39-293151248-gh.circle-artifacts.com/0/intersect-training.github.io/training-links/index.html

**Pull request merged**
