### PR TITLE
Adding photo to blog post

### PR DESCRIPTION
**Pull request by JeffCarver**
I added the image tag to the .md file and added the image file, but it is not rendering properly in my local version.

### CODE REVIEW

**Comment by cosden** [comment]
Let's check after the circle preview is fixed in #48

**Comment by JeffCarver** [comment]
I approved the Circle CI change if you want to merge. Will we need to rerender this one? When I look at it under "artifacts", the announce pages do not seem to render properly. Another option would be just to remove this pull request and start over after merging the other change.

**Comment by cosden** [comment]
Yes, the other PR should have fixe the rendering, but you'll need to rebase to gh-pages to get the latest changes. Or just start over :)

**Comment by JeffCarver** [comment]
I am just going to close the pull request and start over. The edit I made was simple.

**Pull request closed without merging**
