### PR TITLE
Label

### PR DESCRIPTION
**Pull request by morshedniaz**
Bold the text of labels of the training link for better visibility

### CODE REVIEW

**Comment by JeffCarver** [comment]
The change looks good to me. One suggestion, is it possible to insert a blank space before each tag? That would make them a bit more readable.

**Comment by JeffCarver** [comment]
Preview of change: https://56-293151248-gh.circle-artifacts.com/0/intersect-training.github.io/training-links/index.html

**Comment by JeffCarver** [comment]
Looks good to me.

**Review by cosden — APPROVED** [review]
Looks good! Thanks @morshedniaz. We might want to think about putting a legend if it ever gets more complicated than slides/tutorial/hands-on.

**Pull request merged**
