### PR TITLE
Add New link

### PR DESCRIPTION
**Pull request by morshedniaz**
Add a new training material Named : [Intermediate Research Software Development in Python]

### CODE REVIEW

**Comment by JeffCarver** [comment]
Is this pull request ready to review or is it still in draft form?

**Comment by morshedniaz** [comment]
Dear Professor,

I  add the new training link materials you provided. I think it's ready to review. please let me know.

Thank you.

Sincerely yours
Niaz
Md Niaz Morshed
Graduate Research Assistant,
Department of Computer Science,
University of Alabama, Tuscaloosa,
USA.
________________________________
From: JeffCarver ***@***.***>
Sent: Monday, February 7, 2022 11:36 AM
To: INTERSECT-training/intersect-training.github.io ***@***.***>
Cc: Md Niaz Morshed ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [INTERSECT-training/intersect-training.github.io] Add New link (PR #32)


Is this pull request ready to review or is it still in draft form?

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FINTERSECT-training%2Fintersect-training.github.io%2Fpull%2F32%23issuecomment-1031734781&data=04%7C01%7Cmmorshed%40crimson.ua.edu%7Ce82900996be64fdbb8df08d9ea60709a%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637798522199456236%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nu29TepCByV%2FqpKZ9j5WcUA%2BL2%2F5VceFgV%2FFF6FHyko%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVQXILD6CSTPCVJFKB75YSDUZ77LTANCNFSM5NUK3EXA&data=04%7C01%7Cmmorshed%40crimson.ua.edu%7Ce82900996be64fdbb8df08d9ea60709a%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637798522199456236%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Bt6Oxxa%2BQbBOWOiXBeXJixdpqJX10rqwFsQmt5%2FegEE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmmorshed%40crimson.ua.edu%7Ce82900996be64fdbb8df08d9ea60709a%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637798522199456236%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jz6YsP6%2FxX48C163uSOKBsZxeYxFukjMTMJ93WRigVk%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmmorshed%40crimson.ua.edu%7Ce82900996be64fdbb8df08d9ea60709a%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637798522199456236%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7f6mpyCcHjYabBzsGWzFJd%2BKJt6NXmseHVbyzjWb%2BUw%3D&reserved=0>.

**Comment by cosden** [comment]
@morshedniaz Something happened with the git history - it's a mess. I believe you fork is behind. Can you try again with a new PR after you sync with the upstream (this) repository. This might help: https://stackoverflow.com/questions/7244321/how-do-i-update-or-sync-a-forked-repository-on-github

**Comment by morshedniaz** [comment]
Dear professor,

Thank you for your reply. I shall do it soon.

Sincerely yours
Niaz
Md Niaz Morshed
Graduate Research Assistant,
Department of Computer Science,
University of Alabama, Tuscaloosa,
USA.
________________________________
From: Ian Cosden ***@***.***>
Sent: Tuesday, February 8, 2022 5:22 AM
To: INTERSECT-training/intersect-training.github.io ***@***.***>
Cc: Md Niaz Morshed ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [INTERSECT-training/intersect-training.github.io] Add New link (PR #32)


@morshedniaz<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmorshedniaz&data=04%7C01%7Cmmorshed%40crimson.ua.edu%7C61cb95bfacfd44f2a9e508d9eaf53ab5%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637799161244795934%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SrqB%2FhFfMkay%2B17HJR5w3cZrHsEYRDzSZMrulF91xQc%3D&reserved=0> Something happened with the git history - it's a mess. I believe you fork is behind. Can you try again with a new PR after you sync with the upstream (this) repository. This might help: https://stackoverflow.com/questions/7244321/how-do-i-update-or-sync-a-forked-repository-on-github<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F7244321%2Fhow-do-i-update-or-sync-a-forked-repository-on-github&data=04%7C01%7Cmmorshed%40crimson.ua.edu%7C61cb95bfacfd44f2a9e508d9eaf53ab5%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637799161244795934%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qljoYRXCzDkG59Qt8qlvvi4EV24j1%2FEm0aMLKPhaSz4%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FINTERSECT-training%2Fintersect-training.github.io%2Fpull%2F32%23issuecomment-1032499900&data=04%7C01%7Cmmorshed%40crimson.ua.edu%7C61cb95bfacfd44f2a9e508d9eaf53ab5%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637799161244795934%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2Fbw375t%2BEeYAfvdSy5EoW43OLRNAuko29DejIIfG9SI%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVQXILC53QVZ6JMN4KW4C3DU2D4FTANCNFSM5NUK3EXA&data=04%7C01%7Cmmorshed%40crimson.ua.edu%7C61cb95bfacfd44f2a9e508d9eaf53ab5%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637799161244795934%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FwoCUoML0iLcSbkYFJENccbNM6vZXztTzR71fZEo8zc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmmorshed%40crimson.ua.edu%7C61cb95bfacfd44f2a9e508d9eaf53ab5%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637799161244795934%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VU9WClN8dumH3RTUdUBksI7SX7F2J9XQq9k1ZZXhkLU%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmmorshed%40crimson.ua.edu%7C61cb95bfacfd44f2a9e508d9eaf53ab5%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637799161244795934%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Z%2BECAxeaZLMlUNey4QaUAlsjB5iZiklsCvC63C8Je2Q%3D&reserved=0>.

**Pull request closed without merging**
